### ISSUE TITLE
Ichimoku2022_Multithreaded, no exchange specified.

### ISSUE THREAD

**Issue by 000KeyserSoze000** [reuniware/Binance-and-FTX-API-Work#2]
Bonjour,

Merci pour ces ressources.

Sur le fichier Ichimoku2022_Multithreaded, je ne sais pas comment définir l'exchange.

INELIDA Scanner v1.0 - https://twitter.com/IchimokuTrader
Scan started at : 2022-09-25 12:02:33.284530
no exchange specified.

Comment puis-je résoudre ce problème ?  exchanges = {}  # a placeholder for your instances ??

Merci encore, et bonne journée

**Comment by 000KeyserSoze000** [comment]
Désolé, je découvre...
Ichimoku2022_Multithreaded -e BINANCE
Merci

**Comment by reuniware** [comment]
Bonjour, oui voilà c'est ça, il faut utiliser l'option -e pour spécifier l'exchange et l'option -g pour obtenir la liste des exchanges disponibles.

Il faut que j'arrive à trouver du temps pour produire une documentation.

On peut aussi spécifier un filtre avec l'option -f (ex : -f usdt), ce qui scannera tous les actifs qui contiennent le terme "usdt", exemple : Ichimoku2022_Multithreaded -e binance -f usdt

Et une autre option (-gotc) qui permet de scanner les actifs pour lesquels le prix croise le haut du nuage (prix d'ouverture inférieur au haut du nuage et prix de clôture supérieur au haut du nuage). "gtoc" = "getting over the cloud".

Merci pour votre intérêt et n'hésitez pas si vous avez d'autres questions ou suggestions.

**Comment by 000KeyserSoze000** [comment]
Bonjour, et encore merci de ces explications limpides. Je vous ai envoyé un mail samedi ( crytpx....@gmail.com).
Bonne journée, et bon courage !

**Comment by reuniware** [comment]
De rien, c'est normal. Vous avez envoyé l'email sur mon adresse yahoo ou sur mon adresse gmail ?

**Comment by 000KeyserSoze000** [comment]
Sur invest.....ms@yahoo.com

**Comment by reuniware** [comment]
Ah ok, désolé, j'ai dû supprimer votre email par erreur. Si nécessaire n'hésitez pas à me le ré-envoyer. Merci.

**Comment by 000KeyserSoze000** [comment]
C'est envoyé , merci.
